name: Publish Image

on:
  push:
    branches:
      - '**'
    tags:
      - '*'

jobs:
  publish:
    runs-on: self-hosted

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract version info
        id: vars
        run: |
          RAW_NAME="${GITHUB_REF_NAME}"
          SAFE_NAME=$(echo "$RAW_NAME" | tr '/' '-')
          OWNER_LC=$(echo "${GITHUB_REPOSITORY_OWNER}" | tr '[:upper:]' '[:lower:]')
          REPO_NAME=$(basename $GITHUB_REPOSITORY)

          echo "raw_name=$RAW_NAME" >> $GITHUB_OUTPUT
          echo "safe_name=$SAFE_NAME" >> $GITHUB_OUTPUT
          echo "owner=$OWNER_LC" >> $GITHUB_OUTPUT
          echo "repo_name=$REPO_NAME" >> $GITHUB_OUTPUT

      - name: Log in to Dockerhub
        if: ${{ github.repository_owner == 'denverquane' }}
        uses: docker/login-action@v3
        with:
          registry: registry-1.docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push multi-arch image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.repository_owner == 'denverquane' }}
          tags: registry-1.docker.io/${{ steps.vars.outputs.owner }}/${{ steps.vars.outputs.repo_name }}:latest

      - name: Push extra tag (branch or release tag)
        if: ${{ github.repository_owner == 'denverquane' && steps.vars.outputs.raw_name != 'main' }}
        run: |
          docker buildx imagetools create \
            --tag registry-1.docker.io/${{ steps.vars.outputs.owner }}/${{ steps.vars.outputs.repo_name }}:${{ steps.vars.outputs.safe_name }} \
            registry-1.docker.io/${{ steps.vars.outputs.owner }}/${{ steps.vars.outputs.repo_name }}:latest